main:

- name: Home
  url: /
  weight: 10

- name: Publications
  url: /publications/
  weight: 20

- name: Software
  url: /software/
  weight: 30

- name: Projects
  url: /projects/
  weight: 40

- name: Teaching
  url: /courses/
  weight: 50

- name: CV
  url: /uploads/cv_jordi_cortes_martinez.pdf
  weight: 60

- name: Contact
  url: /#contact
  weight: 70
